<?php

namespace AdministracionBundle\Repository;

/**
 * NotificacionUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacionUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
